import { OpeningBook } from "./book";
import data from "./book/perfect-book.json";

/** The bundled Perfect-level opening book (generated by `npm run build:book`). */
export const PERFECT_BOOK = new OpeningBook(data as ConstructorParameters<typeof OpeningBook>[0]);
